### ISSUE TITLE
Add travis CI integration

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#106]
Build PRs and master with Travis CI. For this ticket, simply building the app (running npm install without error etc.) is enough, tests, code style etc. to be done as part of other tickets.

**Comment by cfilby** [comment]
I'll go ahead and take this one on.

**Comment by yasirunilan** [comment]
Can I work on this ?

**Comment by aashutoshrathi** [comment]
Can I work on this one?

**Comment by yasirunilan** [comment]
@jenkoian  can you check, I did some work regarding this.
