### ISSUE TITLE
Add some basic tests

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#107]
Open to tools and libraries to use for this.

**Comment by butlerx** [comment]
eslint for backend code would be good. would be able to enforce `'use strict';` and similar rule
i would recommend the [airbnb eslint](https://www.npmjs.com/package/eslint-config-airbnb) config as a base 
if you use eslint you could aslo then use [eslint handlebars](https://github.com/psbanka/eslint-plugin-hbs)

**Comment by fobos** [comment]
@butlerx I think you commented #108 not this one.

**Comment by cfilby** [comment]
What sort of tests did you have in mind? Unit tests or end to end tests with mocked Github responses?

**Comment by gagyibenedek** [comment]
I'd gladly add unit tests for the JS part.

**Comment by jenkoian** [comment]
Sorry for delayed response, yeah open to either. End to end would make most sense to me? As currently there isn't really much to unit test?

**Comment by gagyibenedek** [comment]
I think both have their value. For me it would make sense to do both.

**Comment by jenkoian** [comment]
@gagyibenedek would welcome a PR if you fancy :)

**Comment by gagyibenedek** [comment]
will do! :)

**Comment by jenkoian** [comment]
Closing in prep for 2018 rewrite.
