### ISSUE TITLE
Add code style checker

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#108]
Add a way of checking code style and have it fail the build (see #106) if the code doesn't adhere. Am open to tools/libraries.

**Comment by cfilby** [comment]
I'll take this on

**Comment by Samoxive** [comment]
For javascript files, ESLint seems to be the go-to choice, maybe we could use one of the existing lint configurations on top of it.

**Comment by mruzekw** [comment]
There's also Prettier as a code formatter.

**Comment by jenkoian** [comment]
ESLint added here https://github.com/jenkoian/hacktoberfest-checker/pull/114
