### ISSUE TITLE
It shows PR, which doesn't even have 'Hacktoberfest' label

### ISSUE THREAD

**Issue by aashutoshrathi** [jenkoian/hacktoberfest-checker#118]
In the description of one's PR in Hacktoberfest, It is showing all the PRs one submitted in October, instead, it should just show the ones which have label `Hacktoberfest`.

**Comment by josephyi** [comment]
The rules for Hacktoberfest state that PRs can be made to _any_ public repo. I think the labels are just to help people find projects in case they want some direction.

**Comment by jenkoian** [comment]
What @josephyi said :)
