### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#123]
See https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ am open to suggestions for format, but would favour something very lightweight.

**Comment by simonstaton** [comment]
Setting one up for you now

**Comment by simonstaton** [comment]
https://github.com/simonstaton/hacktoberfest-checker/pull/1 I have added tests for the acceptance criteria but you can remove this part

**Comment by jenkoian** [comment]
@simonstaton I think you've opened the pull request against your fork?

**Comment by simonstaton** [comment]
Still waking up, here you go - https://github.com/jenkoian/hacktoberfest-checker/pull/124
