### ISSUE TITLE
UI improvements?

### ISSUE THREAD

**Issue by QuadDepo** [jenkoian/hacktoberfest-checker#128]
I know this is only for the time being but some UI could be made, would love to do it. :-)

**Comment by jenkoian** [comment]
Would welcome a PR :)

**Comment by QuadDepo** [comment]
Will try my best :D

**Comment by jbmills327** [comment]
I have an idea that I think might look kind of cool. I would like to add some twinkling stars to make the background look the night sky at dusk.  Do you think this would add to the page at all or would it ruin the minimalistic design?

**Comment by QuadDepo** [comment]
Well we can do it having some micro interactions in the background. @jbmills327 

You wanna help me? i have some time friday

**Comment by jbmills327** [comment]
I might be able to do that Friday afternoon.  I put together a little something but it changed the background to black, twinkling stars and some creepy clouds floating by.  I can push it and them maybe you could take a look and see what you think?

**Comment by QuadDepo** [comment]
@jenkoian you think we can use the official logo?

**Comment by jenkoian** [comment]
@jbmills327 sounds interesting! Looking forward to the PR :)

@QuadDepo I don't think so no

**Comment by jbmills327** [comment]
I made some changes and submitted the PR.  I was just having some fun and it was based on a  tutorial I had played around with a few months ago.  I hope you like it but I totally understand if it is too much. I have never used handlebars before so it is just some basic HTML and CSS.  Thanks for taking a look, I had fun just playing around!

**Comment by jenkoian** [comment]
Closing in prep for 2018 rewrite.
