### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ConsoleTVs** [jenkoian/hacktoberfest-checker#131]
Just letting u know it's not working.

![image](https://user-images.githubusercontent.com/6124435/31097592-18d66a8c-a7c0-11e7-96e3-8d6dd106d885.png)
![image](https://user-images.githubusercontent.com/6124435/31097600-1f06e8be-a7c0-11e7-8a74-62ce25a564ee.png)

https://github.com/pfefferle/atom-php-cs-fixer/pull/71

**Comment by koddsson** [comment]
Hey @ConsoleTVs 👋 

It looks like the PR you linked was opened on September 30th and I think only the PRs made in October count towards Hactoberfest.

**Comment by ConsoleTVs** [comment]
Maybe, but I signed up already hmmm. Thanks for the info tho :)
