### ISSUE TITLE
Add quick access to my personal account

### ISSUE THREAD

**Issue by Fleker** [jenkoian/hacktoberfest-checker#135]
If you add a login button and allow people to login through GitHub, it would allow the site to automatically display their current stats.

Or you could store the last-checked user as a cookie and automatically display that the next time the user opens the site.

**Comment by jenkoian** [comment]
> it would allow the site to automatically display their current stats

Could you elaborate on this? Personally I find it must less effort to just chuck in my username than have to go through the two factor auth rigmarole.

**Comment by Fleker** [comment]
When I go to hacktoberfestchecker.herokuapp.com it would redirect me to https://hacktoberfestchecker.herokuapp.com/?username=fleker

It'd be slightly more convenient, maybe not at the cost of the OAuth work.

You could just store the username in a cookie so when the user visits the main site or a certain page like https://hacktoberfestchecker.herokuapp.com/me it redirects them.

**Comment by jenkoian** [comment]
@Fleker would be open to a PR for the cookie thing, as agree it could be a convenience :)

**Comment by jenkoian** [comment]
Fixed in #183
