### ISSUE TITLE
not responsive on mobile 

### ISSUE THREAD

**Issue by wildan3105** [jenkoian/hacktoberfest-checker#141]
When I search my username account via smartphone, the PR results didn't show the exact same as web result, like this : 

![issue1](https://user-images.githubusercontent.com/7030099/31132444-066c6ece-a887-11e7-9ba7-d3e939188f62.jpg)

**Comment by jenkoian** [comment]
Thanks, would be good to get this fixed, have attached the hacktoberfest label if someone wants to pick it up, else I'll look at it when I get chance 👍

**Comment by wildan3105** [comment]
Hi, actually I could work on this. Do you give me a shot? @jenkoian

**Comment by hosmelq** [comment]
#138 should fix this.
