### ISSUE TITLE
Checker's icons don't distinguish between Merged and Closed PRs

### ISSUE THREAD

**Issue by Zeustopher** [jenkoian/hacktoberfest-checker#142]
The checker's icons don't distinguish between Merged and Closed PRs. They both show as the Merged icon.

A Closed PR should use the "Request" icon but it should be colored Red. That is how Github represents them.

I _think_ the fix would be related to the file https://github.com/jenkoian/hacktoberfest-checker/blob/master/views/partials/prs.hbs. It appears that there are only two states defined - one for "open" and one for "closed".

See line `<div class="fl w-10 pa2 closed">`

There probably needs to be a third state defined so there is "open" (which is the green request icon), "merged" (which is the purple merge icon), and "closed" (which is a red request icon).

Happy Hacktoberfest!

**Comment by Zeustopher** [comment]
Pictures are worth a thousand words:

![image](https://user-images.githubusercontent.com/11470532/31138441-b946c3c0-a82b-11e7-866c-d8421b67d044.png)

**Comment by David-Byrne** [comment]
I can try give this one a shot :smile:

**Comment by David-Byrne** [comment]
Not sure this is such an easy fix. The JSON returned from the API seems to have `state: 'closed'` set for both closed and merged pull requests, as can be seen in [this](https://api.github.com/repos/freedomotic/fd-user-manual/issues/9) and [this](https://api.github.com/repos/freedomotic/fd-user-manual/issues/15)...

We might be able to get the data with another API call but I don't know if it's worth the added complexity.

**Comment by Zeustopher** [comment]
Drats - I thinks you're right... Too bad. Would have been a nice improvement.

**Comment by 4e554c4c** [comment]
I think this can be used to determine whether a pr is closed or merged: https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged
