### ISSUE TITLE
Text overlaps on smaller screens

### ISSUE THREAD

**Issue by kenma9123** [jenkoian/hacktoberfest-checker#145]
There's a bit of problem on smaller screen like for example mobile. The text overlaps the container as you can see on this image.

![image](https://user-images.githubusercontent.com/1641990/31146232-866466fa-a8b8-11e7-8a4e-fea9aec367d2.png)

Update: I created a PR to simply enable ellipsis on the text so it stays on one line

**Comment by abdulamite** [comment]
Maybe we should wrap the contents in a flex container so that the height of the boxes will adjust for the text content?

**Comment by Akatsuki06** [comment]
Yes, test overflows out of the container.

**Comment by hosmelq** [comment]
#138 should fix this.
