### ISSUE TITLE
Bug in created datetime range in GH API query (options) 

### ISSUE THREAD

**Issue by pybites** [jenkoian/hacktoberfest-checker#152]
First of all awesome tool. We're raising a code challenge to make this in py Bottle and will refer people to this as template.

I got an issue: the GUI included this PR which should be outside the range:
https://api.github.com/repos/synedra/irresistible/pulls/4
"created_at": "2017-09-30T21:07:47Z",

controllers/index.js L15

            q: `-label:invalid+created:2017-09-30T00:00:00-12:00..2017-10-31T23:59:59-12:00+type:pr+is:public+author:${username}`

- why label:invalid? Any PR should do ("Find an issue labeled Hacktoberfest, but remember you aren’t limited to those")
- this includes the 30h of Sept
- I am not sure the -12 hours is needed, it seems to exclude the final hours 31st of Oct

For example my buddy Julian opened this PR AUS evening but API converted it to CET as per best practice working with datetimes:
https://api.github.com/repos/pybites/challenges/pulls/107
  "created_at": "2017-10-03T09:02:32Z",

Their site is indeed a bit confusing: "To get a shirt, you must make four pull requests between October 1–31 in any timezone" - but I think as the API returns CET (the 'Z' at the end of 'created_at') we don't have to add/subtract hours. But I could be wrong of course, what do you think?

**Comment by jenkoian** [comment]
> First of all awesome tool. We're raising a code challenge to make this in py Bottle and will refer people to this as template.

😊 

> why label:invalid? Any PR should do ("Find an issue labeled Hacktoberfest, but remember you aren’t limited to those")

It says `-invalid` which is a way of saying 'exclude invalid'. IIRC @digitalocean included this as a way for maintainers to discount PRs from people blatantly spamming to get a t-shirt.

For questions about time zones, please see my response here:
https://github.com/jenkoian/hacktoberfest-checker/pull/104#issuecomment-333376597

**Comment by pybites** [comment]
Good point 👍  

Yeah if it's their way of validating then that's the way. 

2017-10-31T23:59:59-12:00 still seems weird though :)

Thanks for your fast follow up

**Comment by jenkoian** [comment]
@pybites I have the privilege of living in GMT though, so am open to a better way of handling timezones!

**Comment by pybites** [comment]
@jenkoian I think we're good. 

It is indeed a supported way to express TZs in the query: https://developer.github.com/v3/#timezones

Maybe nice if we can contribute a test to see if the outer bound works ...
