### ISSUE TITLE
It shows number of pull requests, instead of number or 'merged pull request'

### ISSUE THREAD

**Issue by hellotunmbi** [jenkoian/hacktoberfest-checker#159]
I submitted 3 pull requests and only 2 were merged.
When I checked on hacktoberfest-checker, it showed 3/4, instead of 2/4

**Comment by jenkoian** [comment]
PRs opened are what counts, irrespective of merged status 👍

**Comment by hellotunmbi** [comment]
Oh really, I didn't know. Thanks for shedding more light!
