### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#17]
Maybe a pumpkin or something?

**Comment by pjhampton** [comment]
Hey @jenkoian!

I can add this in 😄

**Comment by jenkoian** [comment]
@pjhampton awesome! I guess wait until October so it counts towards your score :)

**Comment by vojtasvoboda** [comment]
Fixed by #18

**Comment by jenkoian** [comment]
Thanks @vojtasvoboda not sure if you want to close and re-open in October though so it counts towards your 4 PRs? Also, kinda think @pjhampton had [bagsy'd](http://www.urbandictionary.com/define.php?term=bagsy) this one! :)

**Comment by vojtasvoboda** [comment]
Yes please, let wait till first October 👍

**Comment by pjhampton** [comment]
wat :-| Hmm, I suppose @vojtasvoboda has already done it for some reason.

**Comment by rafaelstz** [comment]
![image](https://cloud.githubusercontent.com/assets/610598/18968439/6666e9da-865f-11e6-9496-4ac8fdeefeea.png)

Remove pumpkin from page title
https://github.com/jenkoian/hacktoberfest-checker/pull/20

Add favicon Pumpkin
https://github.com/jenkoian/hacktoberfest-checker/pull/21

**Comment by pjhampton** [comment]
😂

**Comment by vojtasvoboda** [comment]
Lol, this Hacktoberfest will be fun 😃

**Comment by jenkoian** [comment]
Oh boy - none of the existing PRs will count as they were opened in September. As hacktoberfest stipulates you just need to open a PR, please consider re-opening in October, I'll then merge which one makes most sense. Likely to be @pjhampton to be honest as he offered first. Appreciate everyones interest in the repo though! :)
