### ISSUE TITLE
Invalid PRs being counted

### ISSUE THREAD

**Issue by ayush1999** [jenkoian/hacktoberfest-checker#178]
Apparently, PRs created in my fork of the Hacktoberfest repo are also being counted as Contributions, and closed PRs (closed without merging) also add to valid contributions.

**Comment by palash25** [comment]
I think there is a need to check if a merged PR is submitted to the same repository as that of the issue referenced in the PR.

**Comment by jenkoian** [comment]
All PRs count so long as the repo is open. Doesn’t matter if it’s fork, nor if the PR doesn’t get merged 👍
