### ISSUE TITLE
User result page social media share feature

### ISSUE THREAD

**Issue by jussih** [jenkoian/hacktoberfest-checker#179]
People are sharing screenshots of the Hacktoberfest checker page in Twitter and other social media. Perhaps it would be possible to make the user's result page sharable with Open Graph meta tags so just sharing your result URL would unfurl in Twitter etc. There could also be share buttons like "Tweet this".

http://ogp.me/
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards
https://developers.facebook.com/docs/sharing/webmasters/
https://dev.twitter.com/web/tweet-button

**Comment by kvizdos** [comment]
This is a good idea.

I'll try and work on this!
