### ISSUE TITLE
Image node UI during image loads

### ISSUE THREAD

**Issue by ShavidzeT** [jenkoian/hacktoberfest-checker#181]
There is a ui problem:
iPhone SE
iOS 11
Safari

![](http://www.picz.ge/img/s3/1710/7/a/adb84b0d627c.png)

**Comment by ShavidzeT** [comment]
7c323ffd9b69e97ea25f4680864a74e659bfc164

**Comment by ShavidzeT** [comment]
ui improved commit reference: bf2a0454d5ffb0ff57fd551fcb07aaac5cc97c69

**Comment by jenkoian** [comment]
Fixed in #182
