### ISSUE TITLE
showng current year of fest

### ISSUE THREAD

**Issue by PAPERPANKS** [jenkoian/hacktoberfest-checker#192]
**Desired Output**
![screenshot-2017-10-9 hacktoberfest checker](https://user-images.githubusercontent.com/13312568/31342594-e2ab919c-ad2a-11e7-870d-218b26ba79d0.png)

@jenkoian in which file i have to add function
```
function getYear(){
  var year = (new Date()).getFullYear();
  document.getElementById("currentDate").innerHTML = 
    'Hacktoberfest' + year + 'Checker';
}
```

Also how to call this function in `hacktoberfest-checker/views/index.hbs` file

**Comment by jenkoian** [comment]
Nice idea, but I don't think we need to show the year, the colours already give that a way in a much more subtle and friendly way imo. Thanks though!
