### ISSUE TITLE
Hacktoberfest: To add Facebook share button to the website

### ISSUE THREAD

**Issue by Manveer695** [jenkoian/hacktoberfest-checker#200]
**Current behavior:**
No Facebook share button in the website

**Expected behavior:**
A Facebook share button or link should be available, when the score is shown.

Please add hacktoberfest tag to the issue. Thanks!

**Comment by sharikovvladislav** [comment]
@jenkoian why  you added hacktoberfest tag? 

can I just add it to my projects too? :)

**Comment by jenkoian** [comment]
@sharikovvladislav not sure I understand?

**Comment by sharikovvladislav** [comment]
You added hacktoberfest label.  So now PR which will solve this issue will participate in hacktoberfest event.

Am I right? Only PRs which solves issue with that label will be counted for event?

**Comment by jenkoian** [comment]
Any PR regardless of label or status count. The label is just suggested by Digital Ocean to help get people involved.

**Comment by sharikovvladislav** [comment]
Ok thanks.

**Comment by sinAshish** [comment]
close this.

**Comment by biigpongsatorn** [comment]
https://github.com/jenkoian/hacktoberfest-checker/pull/210

**Comment by Rabinzon** [comment]
@biigpongsatorn you have a bug:)

**Comment by biigpongsatorn** [comment]
@Rabinzon  I fixed it.

**Comment by jenkoian** [comment]
Fixed in #204
