### ISSUE TITLE
[Q] Do your own PRs count toward Hacktober?

### ISSUE THREAD

**Issue by spences10** [jenkoian/hacktoberfest-checker#202]
Love this, thank you ❤️ 

This is a question really, a'la the issue title

I thought that your Hacktober PR quota only went towards projects that are not your own, no?

Currently showing me as 30/4 PRs of which 29 are dependency updates from Greenkeeper.io 🙃

**Comment by spences10** [comment]
Just checked the DO checker and it's the same, so guessing, yes? 🤷‍♂️

**Comment by jenkoian** [comment]
Yeah, any PR, it's encouraged to not be your own repo's but it will still count. See https://github.com/jenkoian/hacktoberfest-checker/pull/186

**Comment by Sammeress** [comment]
Do PRs on Repos that dont have the Hacktober label count?

**Comment by jenkoian** [comment]
@Sammeress see here for details https://hacktoberfest.digitalocean.com/hacktoberfest-update note this app at time of writing is not up to date with this update.
