### ISSUE TITLE
error in css: class .Stars-three

### ISSUE THREAD

**Issue by Thaynannadu** [jenkoian/hacktoberfest-checker#207]
**Current behavior:**
Stars animation does not work.
Error in css, class:**.stars-three**

**Steps to reproduce:**
![captura de tela 2017-10-11 as 13 57 40](https://user-images.githubusercontent.com/16005700/31454728-c73aa426-ae8c-11e7-8470-98cb732067b9.png)

**Comment by jenkoian** [comment]
See #213 and #214
