### ISSUE TITLE
My username receiving 404

### ISSUE THREAD

**Issue by uLan08** [jenkoian/hacktoberfest-checker#212]
**Current behavior:**
When typed `uLan08` in the field it says `Couldn't find any data or we hit an error, err try again?`

**Expected behavior:**
I should see my PR's, status, etc. I get a response when I try `curl https://api.github.com/users/uLan08`

**Steps to reproduce:**
Just type my username on the demo site.

**Comment by jenkoian** [comment]
Thanks for reporting @uLan08! Funnily enough it was because you contributed to a repo called `pullrequests` 😆  Hopefully fixed now 👍

**Comment by uLan08** [comment]
LOL. I was curious as to why my name wasn't showing up.  Thanks!
