### ISSUE TITLE
The page layout doesn't look good because of the stars and clouds style

### ISSUE THREAD

**Issue by kenma9123** [jenkoian/hacktoberfest-checker#213]
**Current behavior:**
With the newly added style UI for the stars and cloud the page layout doesn't look good. Because of the scrollbars. 
![image](https://user-images.githubusercontent.com/1641990/31484029-2f0d6c58-af61-11e7-8aa4-8c9a6fa3a2ce.png)

**Expected behavior:**
it should be a perfect page with no scroll bar since we are only dealing a single section.

**Steps to reproduce:**
Just open the page and try to drag one of the scrollbars

**Comment by jenkoian** [comment]
Hopefully fixed by #214 can someone confirm?

**Comment by f-breidenstein** [comment]
Tested in FF and Chrome. Looks good.
