### ISSUE TITLE
Stars background image and animation not fixed, on scroll it disappears.

### ISSUE THREAD

**Issue by MadhavBahlMD** [jenkoian/hacktoberfest-checker#220]
**Current behavior:**

![image](https://user-images.githubusercontent.com/26179770/31501327-96686c6a-af87-11e7-9c35-324cc2a81e7c.png)

**Expected behavior:**

![image](https://user-images.githubusercontent.com/26179770/31501344-a34683b8-af87-11e7-8cff-3e0826360fc0.png)
This background should be fixed

**Comment by jenkoian** [comment]
@MadhavBahlMD are you able to provide a PR to fix? If not, I'll try and take a look later on 👍

**Comment by MadhavBahlMD** [comment]
I am on it 👍

**Comment by MadhavBahlMD** [comment]
@jenkoian Issue is now fixed 👍 😃
