### ISSUE TITLE
User image is invisible when not hovered

### ISSUE THREAD

**Issue by feimosi** [jenkoian/hacktoberfest-checker#229]
**Current behavior:**
After user data is loaded, the image is not visible until hovered:

![image](https://user-images.githubusercontent.com/5721520/31576807-0e3c806a-b103-11e7-9bdf-dfaf7f6fe2fd.png)

**Expected behavior:**
The image is visible (better UX, mobile devices etc.).

**Steps to reproduce:**
Enter GitHub username and press Enter

The following commit introduced this issue:
https://github.com/jenkoian/hacktoberfest-checker/pull/182/files#diff-506a5a0ceb78b91144bb23a742b4c7f8R7
by adding `o-0` class to the `img`, not sure why it was done.

**Comment by jenkoian** [comment]
@feimosi thanks for reporting, I can't seem to replicate though, do you mind letting me know what browser/OS you are using? Thanks!

**Comment by feimosi** [comment]
Never mind, I've just tested it in Incognito Mode and everything works fine. Looks like some extension is breaking it, so that `o-0` class is not being toggled.
