### ISSUE TITLE
Live hacktoberfest issue ticker

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#23]
Bit more challenging this one but think it'd be quite neat to have some kind of ticker somewhere which pops up with issues recently opened on github with the hacktoberfest label. 

You should be able to use https://developer.github.com/v3/search/#search-issues which you can filter by labels.

**Comment by bmorelli25** [comment]
I might give this a go at somepoint in the next few days. I'm more familiar with react than jQuery, so no promises that I'll be successful, but worth a shot at least.

If all else fails, I'll at least write some tests per #16

**Comment by mattjegan** [comment]
Perhaps you could use the GitHub API to get the issues list? The docs for it are [here](https://developer.github.com/v3/search/#search-issues)

Maybe something along the lines of this:
```
https://api.github.com/search/issues?q=label:hactoberfest&state:open&sort=created&order=asc
```
which should return all issues with the `hactoberfest` tag that are `open` sorted by when they were made.

**Comment by hamzahsarwari** [comment]
Thank you to whoever made this site. It is incredibly amazing! <3

**Comment by Ne3l** [comment]
Did my attempt to fix that (https://github.com/jenkoian/hacktoberfest-checker/pull/32)

The presentation of the issues can be much better also might be interesting letting the user filter the issues by some criteria as github such as programming language.

**Comment by REPTILEHAUS** [comment]
Yeah this  is pretty cool 👍 if you need a hand with adding in any features or stuff let me know

**Comment by jenkoian** [comment]
Thanks @REPTILEHAUS there is an ongoing PR [here](https://github.com/jenkoian/hacktoberfest-checker/pull/32) - feel free to get involved if you wish 👍

**Comment by REPTILEHAUS** [comment]
Cool, Ive had a few whiskeys at the moment but Im actively taking part in Hacktoberfest so Ill certainly start looking into it tomorrow at 12pm

**Comment by jenkoian** [comment]
If anyone is interested in helping make this 'live' there is a brilliant example of using sockets in a node app [here](https://github.com/debugger22/github-audio)

**Comment by jenkoian** [comment]
Thanks to @Ne3l & @games647 hacktoberfest issues are now being brought out on the homepage. I still think it'd be cool to have this live update though so gonna leave this ticket open.

**Comment by redice44** [comment]
I'd like to take a crack at the live update part, if it's still up for grabs. 👍

**Comment by babhishek21** [comment]
@redice44 I'll also be looking into it (for fun). But feel free to go ahead.

**Comment by jenkoian** [comment]
Thank you @redice44
