### ISSUE TITLE
"This is me" functionalist broken in WebKit (Safari)

### ISSUE THREAD

**Issue by josh-** [jenkoian/hacktoberfest-checker#235]
**Current behavior:**
- Clicking "This is me" throws the following exception in WebKit-based browser:

```
[Error] SyntaxError (DOM Exception 12): The string did not match the expected pattern.
	querySelectorAll (zepto.min.js:2:4807)
	qsa (zepto.min.js:2:4807)
	init (zepto.min.js:2:4103)
	r (zepto.min.js:2:4359)
	saveUserPage (main.js:162)
	(anonymous function) (main.js:169)
	proxy (zepto.min.js:2:16155)
```

Furthermore, since this exception is thrown, the value isn't set and the page then doesn't redirect to `/me`

**Expected behavior:**
- Clicking on the "This is me" button saves the current username and redirects to me `/me`

**Steps to reproduce:**
1. Open the site in a WebKit-based browser
2. Click "This is me"
3. Look at browser console

**Comment by jenkoian** [comment]
Fixed in #236
