### ISSUE TITLE
The link to /me has no protocol

### ISSUE THREAD

**Issue by jmerle** [jenkoian/hacktoberfest-checker#237]
**Current behavior:**
After you check the PR's for a user, the "In the future, you can find your PRs by visiting hacktoberfestchecker.herokuapp.com/me on this device." text pops up. However, the link in there has no protocol part, so it links to "https://hacktoberfestchecker.herokuapp.com/hacktoberfestchecker.herokuapp.com/me".

**Expected behavior:**
I expect it to link to "https://hacktoberfestchecker.herokuapp.com/me".

**Steps to reproduce:**
1. Search for any user's PR's.
2. Scroll down to see the "In the future" text.
3. Open the developer tools to see the link is lacking a protocol.

**Comment by jenkoian** [comment]
Good spot, thanks. Are you able to PR a fix, else I'll get on it later.

**Comment by hugomd** [comment]
I'm making a PR now 👍
