### ISSUE TITLE
Should the hacktoberfest checker be timezone agnostic? 

### ISSUE THREAD

**Issue by QzSG** [jenkoian/hacktoberfest-checker#24]
For now, the search query shows that I made 0 pull requests. 
However, it shouldn't it show 2 pull requests that I made today? 
The checker should not be using UTC - 12:00.

I suggest removing the Timezone portion from the search query.

**Comment by QzSG** [comment]
😢 Just realised that despite registrations for Hacktoberfest starting already, pull requests only count from 1st october, I have no idea what timezone though .. sorry for the wrong issue

**Comment by jenkoian** [comment]
Timezone is set like this to allow for various timezones. See this commit from last years official verification script: https://github.com/erikaheidi/hacktoberfest-verify/commit/7807e0db892f7cb82a60cfc612c7b1e8312ef582#diff-c500bedd4010f8fdb804a470483ce893

And this issue which likely prompted it: https://github.com/erikaheidi/hacktoberfest-verify/issues/6
