### ISSUE TITLE
This is me button not working

### ISSUE THREAD

**Issue by kriswep** [jenkoian/hacktoberfest-checker#242]
**Current behavior:**
When clicking on the  `This is me` button after entering the GitHub username doesn't add the username to localstorage, /me route redirect to /

**Expected behavior:**
Clicking on `This is me` button should save current username to localstorage for usage in /me route

**Steps to reproduce:**
- make sure localstorage is empty
- go to home route, enter a username, click on the button `This is me`
- username won't get saved to localstorage

(it works when refreshing with the username query parameter).

**Comment by kriswep** [comment]
I will send a PR for this myself!

**Comment by jenkoian** [comment]
Fixed in #243
