### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL main.js:74: backtick (`) illegal in "old" browser

### ISSUE THREAD

**Issue by Modified** [jenkoian/hacktoberfest-checker#248]
**Current behavior:**

As the title says: "Uncaught SyntaxError: Unexpected token ILLEGAL main.js:74".
**Expected behavior:**

Transpile it for JS (ES5), duh?
**Steps to reproduce:**

Run (ie open this site/app) in an "older" browser.

**Comment by jenkoian** [comment]
What "older" browser are you using?

**Comment by jenkoian** [comment]
Fixed in #262
