### ISSUE TITLE
Is the closed PR considered by Hacktoberfest

### ISSUE THREAD

**Issue by Manveer695** [jenkoian/hacktoberfest-checker#253]
If closed PR isn't considered by Hacktoberfest, then it shouldn't come like this in the checker web page:
**Current behavior:**
![hacktoberfestissue](https://user-images.githubusercontent.com/20307535/31928521-179bacf2-b8b6-11e7-90a3-b0b2985792ca.PNG)

**Expected behavior:**
The number for the PR should be 3/4.

Please discuss the issue in the comments.

**Comment by jenkoian** [comment]
Incorrect, closed PRs count all the same.
