### ISSUE TITLE
the PR limit

### ISSUE THREAD

**Issue by divyam3897** [jenkoian/hacktoberfest-checker#254]
**Current behavior:**

If you have PR greater than 30 it just shows the latest 30/4

**Expected behavior:**
It should show all the Pull requests.

**Comment by jenkoian** [comment]
@divyam3897 you've been too busy! 😆  I guess this is because we're only hitting the first page of results from the API. Will put a hacktoberfest label against this if anyone wants to pick it up, else I'll take a look if I get chance. Thanks for reporting!

**Comment by rvben** [comment]
I just made a PR to fix this issue.

**Comment by krider2010** [comment]
Haha oops - I was working on one at the same time!

**Comment by krider2010** [comment]
My change supports paging through all results rather than just pushing the `per_page` value, if the maintainer wants to offer that?

**Comment by jenkoian** [comment]
Both excellent PRs so merged them both, thanks! :)
