### ISSUE TITLE
Update for 2018

### ISSUE THREAD

**Issue by rosariopfernandes** [jenkoian/hacktoberfest-checker#273]
The [Hacktoberfest site](https://hacktoberfest.digitalocean.com) has already been updated for the 2018 Edition. It now has a different color scheme and you must complete 5 Pull Requests to win the T-shirt.
Needless to say, I'm suggesting the update of this project for this year's edition.

**Comment by jenkoian** [comment]
Thanks for the nudge, hopefully sort something this week :)

**Comment by rosariopfernandes** [comment]
I would be more than happy to contribute with a PR to update the year and the necessary Pull Requests number to win the shirt.
Then you'd only need to worry about changing the color scheme.

**Comment by jenkoian** [comment]
@rosariopfernandes that's very kind, definitely up for some help! What I like about this project is it's a nice lightweight app to help people contribute, so am really keen to do the same this year. One thing I would like to explore though is turning it into a small React app, but keeping it really light weight. As React is so ubiquitous now I think it makes sense, and hopefully it can encourage others who perhaps are looking for an excuse to get involved with some React to get involved. WDYT?

**Comment by rosariopfernandes** [comment]
Wow, sounds good to me.

**Comment by jenkoian** [comment]
Alright, realistically I'm not going to get chance to work on this until the weekend (nothing like leaving it until last minute!) but should be able to review PRs, so feel free to submit anything if you want, else I'll start something on the weekend and assign you to review 👍

**Comment by rosariopfernandes** [comment]
Ah, don't think I'll have any free time before the weekend to learn React. But I'd be happy to review your work.
