### ISSUE TITLE
Needs to be updated for this year's Hacktoberfest

### ISSUE THREAD

**Issue by zac-garby** [jenkoian/hacktoberfest-checker#275]
The website shows my contributions for last October.

**Comment by damiankw** [comment]
I believe the code is updated, but the herokuapp isn't updated yet, it might need to be manually pushed if it doesn't accept auto updates.

**Comment by jenkoian** [comment]
Yep on it, trying to host it on digital ocean this year as they kindly gave me some vouchers. Just waiting for DNS to propagate now I believe.

**Comment by jenkoian** [comment]
Ok deployed to heroku, having some issues with the digital ocean version, will keep trying, but for now consider it released!
