### ISSUE TITLE
doesn't run behind a reverse proxy

### ISSUE THREAD

**Issue by tessus** [jenkoian/hacktoberfest-checker#277]
**Current behavior:**
Several files are not found. e.g.: `tachyons.min.css`, `main.css`, ...

**Expected behavior:**
It should show the web site correctly (the same way as if it were run locally).

**Steps to reproduce:**

- Start with `yarn start`
- Add the following to your local MAMP/LAMP installation (or your production web server):
    ```
    ProxyPass "/hacktoberfest" "http://localhost:5000"
    ProxyPassReverse "/hacktoberfest" "http://localhost:5000"
   ```
- browse to http://localhost/hacktoberfest

**Comment by jenkoian** [comment]
Thanks, I got this working on digital ocean with a reverse proxy, here is the relevant nginx config:

```yaml
location / {
    proxy_pass http://localhost:5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}
```

**Comment by tessus** [comment]
Well, I looked into it in more detail. Your setup works, because you are using a separate virtual host (`hacktoberfest.example.com`) and place it directly in the document root `/`.

As soon as you want to run it in a subdirectory (`example.com/hacktoberfest`), it doesn't work anymore.

This means your app can only be deployed in the root of a virtual host, which can be a problem in the age of web services and docker images.

The reason are constructs like this:

```
<link rel="stylesheet" href="/css/main.css">
```

While in reality they should like like this:

```
<link rel="stylesheet" href="css/main.css">
```

or this:

```
<link rel="stylesheet" href="${DOCUMENT_ROOT}/css/main.css">
```

I was able to fix almost everything. But I ran into 2 issues:

1. The `Check` button does not work, but invoking `http://localhost/hacktoberfest/?username=tessus` directly works
2. The result shows 
    `In the future, you can find your PRs by visiting http://localhost:5000/me on this device.` 
    instead of 
    `In the future, you can find your PRs by visiting http://localhost/hacktoberfest/me on this device.`

**Comment by tessus** [comment]
Btw, here are the changes I've made so far: https://github.com/tessus/hacktoberfest-checker/tree/reverse-proxy-support

However, I believe there's a routing issue still present somewhere since I can't fix above 2 mentioned issues.

**Comment by tessus** [comment]
I also tried your nginx config:

```
location /hacktoberfest/ {
    proxy_pass http://localhost:5000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}
```

Same issues as with Apache, which basically confirms it is not a reverse proxy issue, but a routing inconsistency in the nodejs app. Unfortunately I know too little about nodejs so I can't figure this out myself.

For some reason, the change of the form action in https://github.com/tessus/hacktoberfest-checker/blob/reverse-proxy-support/views/index.hbs#L4 from `"/"` to `""` did not solve the issue.

Every time I click on `Check`, I can see the following in the nodejs output:

```
GET /undefined 404 1.310 ms - 148
```

**Comment by tessus** [comment]
Unfortunately no.

Because the hostname is the second issue (see https://github.com/jenkoian/hacktoberfest-checker/issues/277#issuecomment-425891175) in a reverse proxy situation:

The result shows
`... your PRs by visiting http://localhost:5000/me on ...`
instead of
`... your PRs by visiting http://localhost/hacktoberfest/me on ...`

**Comment by tessus** [comment]
Maybe, I just don't know how. Maybe by checking if any `X-Forwarded-*` headers are set and if so, use those instead. I have to check the js reference on how to do that.

While this might solve problem number 2, it most likely won't fix problem number 1. I even tried hardcoding `/hacktoberfest` (also tried the full hostname and path) in the form action (for testing purposes), but this didn't help either.
Thus I doubt that prefixing the path `/` with the hostname would change anything.  

I'm still a bit puzzled by the fact that it doesn't work out of the box. I mean, imagine a few of these nodejs applications on one machine. Now, most deployments don't use a virtual host per container, but reverse proxy the apps like `example.com/app1`, `example.com/app2` , `example.com/app3` , ...
But these apps don't have the location hardcoded, but are location agnostic. e.g. the app in container1 could be running on `/app1`, `/app2`, or `/app3`, ...

But maybe I'm missing something...

**Comment by tessus** [comment]
Ok, I've found additional absolute references. After replacing them with relative references, the app runs behind a reverse proxy - mostly.

2 last issues (but I think I'm getting closer):

- the requested path is never transmitted to nodejs (e.g. when accessing `http://localhost/hacktoberfest`), the path in nodejs still  shows `/` instead of `/hacktoberfest`:

    ```
    var url_parts = url.parse(req.url); 
    console.log(url_parts);
    console.log(url_parts.pathname);
    ```
   This is lolgical, because `/hacktoberfest` is mapped to `http://localhost:5000`, thus the requests landing there consist of everything after `/hacktoberfest`. I'm wondering how other nodejs apps handle such a situation. As a workaround I could send an `X-Path-Info` header and parse that in nodejs. However, I don't think this is a real solution, because it makes the app location aware, which it shouldn't be. The app should run under any directory whatsoever.
- the `/me` page stopped working (no idea why that is)

I think I'm at a loss. I've never really worked with nodejs (nor js for that matter) and thus my knowledge in this area is basically non-existent. I'd love to look into it when I have more time, but until then I'm stuck...

...unless you have any additional ideas.
