### ISSUE TITLE
Display number of PRs opened within hacktoberfest

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#281]
If you look at https://hacktoberfest.digitalocean.com/details it mentions the first 50,000 registered people will be eligible for the t-shirt. Now obviously we don't have access to the number of people registered but it may still be quite nice to display the total number of PRs opened in October. This is of course if we can indeed get such information from the Github API.

**Comment by chgasparoto** [comment]
I'll take a look.

**Comment by omergulen** [comment]
It seems like we can't do direct search on GitHub API, hence we need to find issues created after October 2018 and labeled with hacktoberfest and then find their PR's.

**Comment by tanmayrajani** [comment]
> It seems like we can't do direct search on GitHub API, hence we need to find issues created after October 2018 and labeled with hacktoberfest and then find their PR's.

Wouldn't that be misleading? I mean, the issue doesn't need to be opened in October (AFAIK), it doesn't need to contain the Hacktoberfest label.

**Comment by omergulen** [comment]
AFAIK it needs to be, also we need to get PR's, not issues as in #292. It needs to be fixed, correct me if I am wrong.

**Comment by mtpjr88** [comment]
is someone working on this or can I take it?

**Comment by chgasparoto** [comment]
@mtpjr88 there is a discussion on #292

**Comment by sidvishnoi** [comment]
In case no one has noticed it, Hacktoberfest site has an API:
https://hacktoberfest.digitalocean.com/api/statistics

**Comment by jenkoian** [comment]
@sidvishnoi good spot! :) suspect using that would be against their T&C's but worth asking I think.

**Comment by sidvishnoi** [comment]
Looking at that `last_updated_at` timestamp, looks like they update it once per day. Maybe we can store and update it by a cron job (or even manually)
