### ISSUE TITLE
Update open graph thumbnail

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#282]
When [mentioning the site on social media sites](https://twitter.com/jenko/status/1046812330502365184) it will use [this image](https://github.com/jenkoian/hacktoberfest-checker/blob/master/public/img/og.png) for its thumbnail. It needs to be updated with this years colour scheme.

**Comment by ismailuddin** [comment]
I'll be happy to replace that!

**Comment by omergulen** [comment]
I'm gonna add some color options, so you can choose one.

**Comment by omergulen** [comment]
Done.

**Comment by jenkoian** [comment]
Fixed in #285
