### ISSUE TITLE
Use Github GraphQL API

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#283]
This is kind of a hard pick, but I *really* like graphql and think github have a nice graphql API. A fair bit of a work, but certainly not an easy pick, but might be quite nice to use the graphql API over the existing REST one.

**Comment by marvinkome** [comment]
Can you give a full detail about the issue? are we trying to replace the REST API with GraphQL or use graph on top rest API? Also, I'll love to pick it, I'm excited about GraphQL and Apollo

**Comment by marvinkome** [comment]
For checking if a PR has been merged we can use GraphQL too I guess it'll just be another field in the query, I'm not really sure.

**Comment by nunsie** [comment]
nice work on this @jenkoian  would be keen to contribute to gql integration as well, probably see the query looking something like:

```
query {
	user(login: "nunsie"){
		pullRequests(first: 10) {
			nodes {
				state
				author {
					avatarUrl
					login
					url
				}
				createdAt
				repository {
					name
					url
				}
			}
		}
	}
}
```

although would need to add a date filter on the pr's.

Would love to implement this on a react frontend, will you be pushing the react branch you mentioned in the readme anytime soon? 😄

**Comment by jenkoian** [comment]
@nunsie nice, yeah sorry will get that react branch up soon 👍
