### ISSUE TITLE
Remove no longer used assets

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#284]
Have some leftover assets which are no longer used, be good if they could be removed. e.g. https://github.com/jenkoian/hacktoberfest-checker/blob/master/public/img/clouds.png and https://github.com/jenkoian/hacktoberfest-checker/blob/master/public/img/stars.png

**Comment by nicoffee** [comment]
I'l take it

**Comment by jenkoian** [comment]
Fixed in #289
