### ISSUE TITLE
Replace tachyons with tailwind

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#286]
I love tachyons and think it works really nicely on this app. However, I'm a fan of the full stack radio podcast and subsequently really intrigued and eager to try out tailwind. 

It's potentially a fair amount of work because you'd likely need to replace all the classes used and probably also some of the custom styles, but would love to give tailwind a whirl.

https://tailwindcss.com/

**Comment by zjael** [comment]
I will give it a shot. 🤞

**Comment by jenkoian** [comment]
Fixed in #299
