### ISSUE TITLE
Docker build: Expected node version >= `8.0.0` while docker file has `6-alpine`

### ISSUE THREAD

**Issue by AhsanAyaz** [jenkoian/hacktoberfest-checker#295]
PS: **I'm working on the fix**

--

**Current behavior:**

The app doesn't work on docker because it throws the following error while building
```
error hacktoberfest-checker@3.0.2: The engine "node" is incompatible with this module. Expected version ">=8.0.0".
error Found incompatible module
```

**Expected behavior:**
Should build the app correctly using node version 8

**Steps to reproduce:**
Clone the repository, make sure you're running Docker.
Run `docker build -t hacktoberfest-checker .`

**Comment by jenkoian** [comment]
Fixed in #296
