### ISSUE TITLE
Update Pull Request template

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#304]
I don't think the existing pull request template is great, so would like to update it. Am open to ideas of what it should be, or even if we need one at all?

One PR template I came across recently which I really liked was this: https://raw.githubusercontent.com/timber/timber/master/.github/PULL_REQUEST_TEMPLATE.md although the messages will likely need to be tweaked as this project isn't as big as that one.

**Comment by deneuv34** [comment]
Cool!
> One PR template I came across recently which I really liked was this: https://raw.githubusercontent.com/timber/timber/master/.github/PULL_REQUEST_TEMPLATE.md although the messages will likely need to be tweaked as this project isn't as big as that one.

About the sample template. I want to discuss, how about we add the `Screenshot` section for optional section?

**Comment by yeshijinsel** [comment]
I wanna take this issue

**Comment by jenkoian** [comment]
@yeshijinsel about to close this one as someone has already picked it up, thanks though!
