### ISSUE TITLE
Sort out npm scripts.

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#309]
There are a few npm scripts, some of which do things like compile with babel etc. However, it seems we're using this in dev then committing the compiled assets. I think we should probably be ignoring these from git and doing this as part of the start task.

I'm wondering if anyone fancies picking this housekeeping up?

**Comment by mstruebing** [comment]
I'll take care :+1:

**Comment by mstruebing** [comment]
@jenkoian you need to close this issue manually.

**Comment by jenkoian** [comment]
Fixed in #311
