### ISSUE TITLE
Feature Request: Add Microsoft's Participation in Hacktoberfest

### ISSUE THREAD

**Issue by crweiner** [jenkoian/hacktoberfest-checker#317]
**Current behavior:**
Currently, this project tracks all PR's a person makes, regardless of what the repo is.

**Desired behavior:**
Microsoft has thrown their hat into the ring with their own t-shirt giveaway for Hacktoberfest, separately from DigitialOcean/Github/Twilio (even though they own Github now), when you make a meaningful PR on their own open source repos. 

See their blog posts:
https://open.microsoft.com/2018/09/18/hacktoberfest-2018-microsoft/
https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/

Per their announcement, you need to register with Microsoft separately to get their shirt as well:

> For all Hacktoberfest information please visit: https://aka.ms/hacktoberfest
> 
> # How to participate
> 1. **Find a project that looks interesting**. You can browse all our of repos on https://opensource.microsoft.com and filter by keyword, trending, stars, forks, tags, and more.
> 2. Perhaps you already have a great idea for improving the project. If not, **browse the list of open issues**. My favorite tip: look for issues labeled help-wanted or good-first-issue.
> 3. **Make a Pull Request** to improve the project’s code or documentation.
> 4. **[Important]** Complete [this form](https://aka.ms/hacktoberfestshirt) to make sure we enter you in the challenge and register your participation. We’ll send instructions for receiving your shirt after Hacktoberfest ends.
> 
> …that’s it!

See https://github.com/Microsoft/Hacktoberfest

So, it would be wonderful if this project could also track if you've made a PR in a Microsoft repo, and remind people to sign up for their second shirt as well. 

Thoughts?

**Comment by jenkoian** [comment]
Nice! This is a really neat idea! Shouldn't be too tricky to do either, just see if the repo of a PR is owned by microsoft and tally them up if any to present a score, possibly we can add a label to the PR too (like we do with the hacktoberfest label).

**Comment by crweiner** [comment]
Glad you like the idea, and I hope others find it useful too!
I have a branch to work on it [here](https://github.com/crweiner/hacktoberfest-checker/tree/microsoft), but I honestly don't have that much time at the moment and someone else will probably be able to do it faster and better than me. :smile: 
They have a lot of repos, and apparently anything on [this list](https://opensource.microsoft.com/) will qualify, not just https://github.com/Microsoft.

**Comment by crweiner** [comment]
So, I recently found out that there are at least a few other companies that are also giving away items for Hacktoberfest. While DigitalOcean and Microsoft are obviously the largest, there are several smaller tech companies giving out shirts and stickers as well.

I'm compiling a list of them here: https://github.com/crweiner/hacktoberfest-swag-list

Obviously, this checker doesn't need to be updated to keep track of all of these other companies offering something, so I was wondering where you would like to draw the line? Stick with the main DigitalOcean giveaway and close this request? Add a large company like Microsoft and their participation (considering that it's easier to get their t-shirt this year than it is from DigitalOcean)? 

I wanted to get your opinion, @jenkoian, as I don't want my proposal to add Microsoft's participation in Hacktoberfest to snowball into requesting that this app tracks every other company too.

I'll still keep working on integrating the Microsoft repos in the meantime.

Thanks for sharing your thoughts and starting this great project for the Hacktoberfest community. :smile:

**Comment by jenkoian** [comment]
@crweiner yeah am aware there are a few others, my stand on it, we'll support as many as people wish to contribute! The caveat being that the page still feels pretty light. 😃

**Comment by MiniMarvin** [comment]
May I start adding tips to the user to enter those other hacktoberfest contests? I found out about microsoft just now and I think it is already a good think to add here

**Comment by jenkoian** [comment]
Sure!
