### ISSUE TITLE
React Version of Hacktoberfest Checker

### ISSUE THREAD

**Issue by frextrite** [jenkoian/hacktoberfest-checker#319]
**Current behavior:**

Couldn't find the branch with the react version as stated in the README

**Expected behavior:**

expected to find a branch with react version of the website as stated in the README

**Steps to reproduce:**

check branches

Maybe open source the react version so that the community could contribute to it.

**Comment by jenkoian** [comment]
yep, sorry been really short of time, the react branch is really early/small but will get that up soon promise!

**Comment by frextrite** [comment]
Great! Eagerly waiting for it.

**Comment by AhsanAyaz** [comment]
@jenkoian I'd love to do it if the title had `Angular` 😄 

_All frameworks are good_

**Comment by jenkoian** [comment]
Merged! Thanks again @rafaelklaessen

**Comment by rafaelklaessen** [comment]
:smile:
