### ISSUE TITLE
Change every herokuapp URL to https://hacktoberfestchecker.jenko.me/

### ISSUE THREAD

**Issue by coderwassananmol** [jenkoian/hacktoberfest-checker#325]
**Current behavior:**

Currently, there are links in app.json and prs.hbs which have link to herokuapp.

**Expected behavior:**

It should be set to default to [https://hacktoberfestchecker.jenko.me](https://hacktoberfestchecker.jenko.me)

**Steps to reproduce:**

**Comment by Busterz** [comment]
Hi, I have addressed this issue - PR (Updated app.json and prs.hbs files #327). Please review, thanks!

**Comment by jenkoian** [comment]
Good catch thanks

**Comment by Busterz** [comment]
@coderwassananmol Take note that there is no need to change the link in prs.hbs anymore because it has been changed to a dynamic one.

**Comment by jenkoian** [comment]
Thanks for raising this, think it can be closed now though.
