### ISSUE TITLE
Open / Rejected PRs count?

### ISSUE THREAD

**Issue by sanspace** [jenkoian/hacktoberfest-checker#34]
May be it's a question for Digital Ocean team. But, as usual they don't seem to have a repo for the hacktoberfest site.

Any PR made during the window counts or it needs to be merged?

**Comment by LauraNK** [comment]
Nope, they don't need to be merged.

>"(Pull requests do not have to be merged and accepted; as long as they've been opened between the very start of October 1 and the very end of October 31, they count towards a free T-shirt.)"

From [their blog](https://www.digitalocean.com/company/blog/ready-set-hacktoberfest/).

**Comment by sanspace** [comment]
Good to know. Thank you!
