### ISSUE TITLE
Bug: '0' displayed in pull request list when no pull requests are made

### ISSUE THREAD

**Issue by yikjin** [jenkoian/hacktoberfest-checker#340]
**Current behavior:**
Look up any user who has no pull requests made during the month of October. A `0` is displayed where the list of pull requests should be.

![The zero bug](https://user-images.githubusercontent.com/34995304/47683528-cce2cf00-dc0a-11e8-81b2-06250b1b2fb2.jpg)

**Expected behavior:**
The list of pull requests should not be visible at all.

**Steps to reproduce:**
1. Look up any user who has no pull requests made during the month of October (eg. https://hacktoberfestchecker.jenko.me/user/octocat).
2. A `0` is displayed where the list of pull requests should be.

**Comment by jenkoian** [comment]
Thanks for reporting, will take a look when I get chance 👍
