### ISSUE TITLE
how to run the react app behind a reverse proxy?

### ISSUE THREAD

**Issue by tessus** [jenkoian/hacktoberfest-checker#346]
How do I run the new react app behind a reverse proxy?

Previously I set the following in my Apache conf:

```
ProxyPass "/hacktoberfest/" "http://localhost:5000/"
ProxyPassReverse "/hacktoberfest/" "http://localhost:5000/"
```

And this in `.env`:

```
APP_URL=http://localhost/hacktoberfest
```

**Comment by tessus** [comment]
any comment? I could really use some help.

**Comment by jenkoian** [comment]
Sorry struggling for time, it should still work the same but the env var name has changed and you'll need to run build script first.

**Comment by tessus** [comment]
Hmm, why did you close this issue. Nonody has ever answered my question:

right, but now there are 2 variables REACT_APP_HOSTNAME and REACT_APP_API_URL.
Previously it was very clear. The app ran on port X and you pointed ProxyPass to that port and you set the external URL.
But now there are 2 URLs to set (frontend, api) and no external URL.

How do I set them correctly?

**Comment by tessus** [comment]
Yep, whatever.
