### ISSUE TITLE
Update App for 2019

### ISSUE THREAD

**Issue by siddhantvirus** [jenkoian/hacktoberfest-checker#357]
Since this is not exactly a bug , I couldn't follow the default template for issues for this repository.

The app doesn't work for Hacktoberfest 2019. 

1.We need to update the minimum pull requests to 4 from 5 , which is the norm last year . 
I believe we need to edit the file at src/pages/User/components/PullRequests/pullRequestAmount.js , and change the const value .
https://github.com/jenkoian/hacktoberfest-checker/blob/85afaf7adc00d0e0489d7b561ab6a29206936451/src/pages/User/components/PullRequests/pullRequestAmount.js#L1

2.We also need to fix the searchyear  line at 
https://github.com/jenkoian/hacktoberfest-checker/blob/85afaf7adc00d0e0489d7b561ab6a29206936451/api/controllers/pr/findPrs/loadPrs.js#L12

to make sure people in certain timezones are not show results of the previous year on !st October (current year) , like it does for me at GMT +5:30 right now , 

or the build query line at 

https://github.com/jenkoian/hacktoberfest-checker/blob/85afaf7adc00d0e0489d7b561ab6a29206936451/api/controllers/pr/findPrs/loadPrs.js#L6

I'm sorry if i failed to understand the code for fixing 2.

And i would love to fix 1. and try fixing 2. 

Thank You !

**Comment by jenkoian** [comment]
Hey thanks for this, new update coming soon (before 00:01 GMT I hope!) I'll get back to you tomorrow (after a sleep :))

**Comment by siddhantvirus** [comment]
I would love to see the new update . Can't wait :) 

Please let me know if I can help in anyway.

**Comment by jenkoian** [comment]
Thanks @siddhantvirus - new version is up, it's late here so going to bed, but will look through your points closely tomorrow. Thanks!

**Comment by frenck** [comment]
Unfortunately, it is still showing me the PRs of last year :(

**Comment by jenkoian** [comment]
You’re right, damnit - if you are able to submit a pr I will merge otherwise it will have to wait until morning - apologies for the bug!

**Comment by jenkoian** [comment]
Ok this fixed itself, I imagine it's a timezone thing, possibly related to server time too. Regarding the other points...

> We need to update the minimum pull requests to 4 from 5

Thanks for the fix @siddhantvirus 

> We also need to fix the searchyear line at

So this is interesting, currently it dips into September 30th in some timezones (and November the 1st) due to us catering for the various time zones around the world, i.e. if you submit a PR 00:01 on November 1st GMT it will still count as it was submitted in October in some time zone. I *think* this is correct with the rules and certainly has been in previous years, but perhaps something I can clarify with Digital Ocean.

**Comment by frenck** [comment]
It is based on the earliest and latest timezones.

Between SST (Samoa Standard Time, UTC-11:00) & LINT (Line Islands Time, UTC+14:00).
This covers all timezones in the world.

**Comment by jenkoian** [comment]
@frenck thanks, I think that's what I was trying to suggest, although maybe I need to update my timings

**Comment by jasminexie** [comment]
Hi! I was using this site for this years' Hacktoberfest, and I noticed that although the number of PRs required has been changed to 4 for this year, the user info text in `components/PullRequests/UserInfo/ResultMessage/getResultMessage.js` has not changed. 

```
const messages = [
  "It's not too late to start!",
  'Off to a great start, keep going!',
  'Keep it up!',
  "Nice! Now, don't stop!",
  'So close!',
  'Way to go!',
  "Now you're just showing off!"
];
```

So 4/4 shows "So close!".

**Comment by jenkoian** [comment]
@jasminexie that is a great spot! (and also massive props to getting to 4 so early!!) - would you be able to make it 5 and providing a fix?

**Comment by jasminexie** [comment]
Thanks. Right now it’s a National Holiday where I live so I have a lot of time on my hands. I could make a PR for this, but I also believe that maintainers are usually proud of their projects and would like to customize and/or show off where possible (at least I’m guilty of that 🤣) and I thought you might like to change the messages yourself. “w00t awesome! 🎃 “ or something like that.

Or I could just provide a boring little fix 😄

**Comment by jenkoian** [comment]
@jasminexie 😃 what I'm most proud about this project is how the community has really helped bring it on and make it better than I ever imagined. I'm sure whatever wording you choose would not be boring 🙂. If you wanted to provide a PR I'd look forward to reviewing it, but no worries if not, I'll make the change shortly 🙂

**Comment by jenkoian** [comment]
Can this be closed, there's nothing the app is missing now?

**Comment by siddhantvirus** [comment]
Yes :)
