### ISSUE TITLE
Closed but unmerged pull requests are being counted

### ISSUE THREAD

**Issue by prashcr** [jenkoian/hacktoberfest-checker#36]
[Example](https://hacktoberfestchecker.herokuapp.com/?username=prashcr)

The third PR has been closed but not merged.

I don't think they count...do they?

**Comment by jenkoian** [comment]
See https://github.com/jenkoian/hacktoberfest-checker/issues/34#issuecomment-251018270 but yeah any PR counts, doesn't need to be merged.
