### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#367]
There are a few things on the app which I think could do with some explaining. For example the new 'pending' text and why some PRs show as counting but the date may be Sept 30th or Nov 1st. 

I think the best thing would be to have a new page called FAQs which answers these curiosities.

Questions I have in mind:

Q: Why do some PRs have 'Pending' next to them?

A: There is a grace period this year which means that a PR must be open (or merged) for at least a week in order to give maintainers the chance to mark issues as invalid. Therefore, the PR will be marked as 'Pending' until that grace period has expired.

Q: Why do some PRs show outside of October?

A: If you've submitted a PR on the last day of September or the first day of November, there is a chance of it counting *if it is October in any timezone*.

--

Are there are any other questions people can think of?

**Comment by wale-bant** [comment]
Hi, can I work on adding the FAQ page and update it as more questions come up?

**Comment by hjaintech** [comment]
Hi @jenkoian , I have fixed this issue in [this](https://github.com/jenkoian/hacktoberfest-checker/pull/368) PR. Please review and merge.

**Comment by jenkoian** [comment]
To clarify, I mean an FAQs page on the web app not in the README.

**Comment by siddhantvirus** [comment]
@jenkoian do you want an js page for the same ?

**Comment by DirtySoc** [comment]
Not sure if you are assigning this issue or note @jenkoian but I started working on adding a FAQ page to the web app.

**Comment by jenkoian** [comment]
@DirtySoc hadn’t planned on assigning but feel free to raise a PR when you’re done 🙂

**Comment by DirtySoc** [comment]
@jenkoian could you take a look at my fork and let me know why my FAQ div's are not rendering? I don't have much experience with CSS and I think that the divs are getting squished? I'm not sure.
https://github.com/DirtySoc/hacktoberfest-checker

**Comment by Busterz** [comment]
Hi @jenkoian , since this issue is still listed, can we still do a PR on this? or it is closed already?

**Comment by DirtySoc** [comment]
Hey @Busterz, I have an open PR I'm working on to solve this issue, but AFAIK its a free for all. If you want to try yourself go ahead and fork/branch and create a PR.

**Comment by jenkoian** [comment]
@Busterz @DirtySoc have reviewed that PR and I had a few little things, the main thing is the design of the FAQs themselves, if you want to take a stab at that, maybe branch from @DirtySoc's branch or something?

**Comment by Busterz** [comment]
I was actually looking at the other two new issues #379 and #380  but apparently there are people working on them. Guess I will take a look at @DirtySoc 's branch and give it a shot @jenkoian

**Comment by Busterz** [comment]
Hey @jenkoian , if you don't mind, I just want to take this opportunity to thank you for starting this site because i have been using it for 3 years straight now for Hacktoberfest.

**Comment by Busterz** [comment]
Hi @jenkoian , could you please review my PR #388 for this? Thank you

**Comment by jenkoian** [comment]
Thanks for your kind words @Busterz - been away for the weekend but will catch up today 👍

**Comment by Busterz** [comment]
Hi @jenkoian , I have made changes to your comments on my PR #388 . Than you

**Comment by Busterz** [comment]
Hope the design is at least to your liking @jenkoian

**Comment by Zeustopher** [comment]
I liked the idea of a FAQ page and wanted to contribute to it. I've opened #391 adding a question and answer about the need for this project now that the official Profile shows your progress.

:heart: :jack_o_lantern:

**Comment by jenkoian** [comment]
This is all up and running, thanks to everyone who helped out ❤️
