### ISSUE TITLE
Pull request in user page not aligned

### ISSUE THREAD

**Issue by vccolombo** [jenkoian/hacktoberfest-checker#376]
Hello!

As can be seen in [this image](https://imgur.com/a/qBm7psP), it looks that some PR entries (maybe all opened PRs?) are unaligned (at least for me).

I tested it in both firefox and chrome, Ubuntu 16.04. My bet is that the div class for it is wrong, as it seems that hacktoberfestp-4 does not exists. I really don't know html and css, so I may be wrong, but I managed to fix it by changing hacktoberfestp-4 to only p-4, as in the others divs.

Is there anyone with the same problem?

**Comment by jenkoian** [comment]
Thanks, I've noticed this too!
