### ISSUE TITLE
Horizontal scrollbar on a fitting page

### ISSUE THREAD

**Issue by Busterz** [jenkoian/hacktoberfest-checker#378]
I am not sure if this is an issue but I think it is pretty unusual for a seemingly fitting page to the browser. There exists a horizontal scrollbar like shown below.

![image](https://user-images.githubusercontent.com/15963091/66129840-3b9e8880-e623-11e9-9440-0e6b7695b7de.png)

When scroll it to the right, I noticed this blank segment as shown on the screenshot above.

Let me know if there is any specific cause to this @jenkoian  because from the inspection there seems to be nothing causing it. However, I know of a quick fix to this if you want it.

**Comment by jenkoian** [comment]
Thanks @Busterz I think it's been fixed as part of this PR which I hope to merge soon https://github.com/jenkoian/hacktoberfest-checker/pull/373

**Comment by Busterz** [comment]
Thanks! Looking forward to the changes.
