### ISSUE TITLE
Glowy title

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#379]
I really like the glowy effect on this VS code theme: https://github.com/robb0wen/synthwave-vscode and was wondering if we could do something similar with the `Hacktober` part of the title on the site. 

The CSS from the theme is here: https://github.com/robb0wen/synthwave-vscode/blob/master/synthwave84.css for inspiration

**Comment by echowebid** [comment]
Please review :) #384

**Comment by jenkoian** [comment]
Thanks for all the contributions toward this one, I'm not sure if it actually works on a title at this size, dunno it just looks off to me?

**Comment by thatzacdavis** [comment]
I do think the yellow is the way to go, maybe just more subtle like you said.
