### ISSUE TITLE
Incorrect Date Frame

### ISSUE THREAD

**Issue by dmlittle** [jenkoian/hacktoberfest-checker#39]
Looking at the Github PR query, it is currently fetching PR requests filtered by time between `2016-09-30T00:00:00-12:00` and `2016-10-31T23:59:59-12:00`. Shouldn't it start on October 1st instead of September 30th? I noticed this because I have 4 PRs in September 30th that are currently being counted which I don't think they should be.

**Comment by jenkoian** [comment]
Bit of an explanation here: https://github.com/jenkoian/hacktoberfest-checker/issues/24
