### ISSUE TITLE
Animate GitHub corner

### ISSUE THREAD

**Issue by NNTin** [jenkoian/hacktoberfest-checker#393]
I have the same GitHub corner but I added some CSS magic. See here: https://nntin.github.io/discord-logo/  

Hover over the GitHub icon on the top right and you see him slowly growing bigger, eventually he has some glasses, a text appears that says `click`.

I also got my [GitHub corner from tholman](http://tholman.com/github-corners/) but I extended it further when I did the Discord animations.

Maybe brainstorm if further animation is wanted and if so what kind of animations.

**Comment by jenkoian** [comment]
Nice, I like the subtle animation on the tholman one you linked to, will have a look into more a bit later, thanks!
