### ISSUE TITLE
Add CD deploy preview

### ISSUE THREAD

**Issue by NNTin** [jenkoian/hacktoberfest-checker#395]
Netlify or a comparable continuous deployment tool.

Advantage: When people create a pull request a new temporary website gets deployed allowing you to view the changes without having to build the website yourself.  
It allows easy persistent sharing and showing changes through the web opposed to only seeing the changes temporary and locally.

Example:
https://github.com/mmistakes/made-mistakes-jekyll/pulls
![image](https://user-images.githubusercontent.com/18033169/66754841-2a614180-ee97-11e9-9a9e-bc75f347bd66.png)
https://deploy-preview-705--mademistakes.netlify.com/

**Comment by jenkoian** [comment]
@NNTin yeah have considered, would be nice if I get time 👍
