### ISSUE TITLE
Reduce generated CSS size (purge css etc.)

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#397]
Tailwind is fantastic, but the generated CSS file is coming in at over 1mb 😱 - we should look at using Purge CSS to reduce this, see: https://tailwindcss.com/docs/controlling-file-size/#setting-up-purgecss we should also look to employ some of the other tactics outlined on that page to reduce the size.

**Comment by radiantly** [comment]
I'm on this!
