### ISSUE TITLE
Add graph of PRs opened throughout Hacktoberfest

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#40]
Was thinking it'd be cool to have a graph or like a sparkline somewhere of PRs opened throughout October, maybe we can dip a little in to September also to give a comparison.

Should be able to call something like https://api.github.com/search/issues?q=created:2016-09-30T00:00:00-12:00..2016-10-01T23:59:59-12:00&sort=created&order=asc&type=pr which will give you the `total_count` at the top. We can then use this total count for each time period (each day I guess) and then plot our graph. If that ends up firing off too many API requests (it could potentially mean over 30 API requests per request) then possibly we can just give that one API request the complete range (e.g. mid september to end of october) and then traverse the results to work out when the PRs were created. Results are paginated though so would need to take that into account also.

**Comment by darrylpargeter** [comment]
Hey @jenkoian 

Is this still open to be worked on?

**Comment by jenkoian** [comment]
@darrylpargeter yep! :)

**Comment by darrylpargeter** [comment]
Then I shall make a start, any preference on charting tools? or would I be free to use the one I know?

**Comment by jenkoian** [comment]
No preference on charting tools, I really like the sparklines on the repositories view on GitHub e.g. https://github.com/jenkoian?tab=repositories althougj we would need a bit more info like an axis with labels I suspect but yeah generally up to you :)

**Comment by darrylpargeter** [comment]
so a minimalist Line graph it is ^^, should it be displayed on the main page or on a different page?

**Comment by jenkoian** [comment]
Was thinking the main page but could put it on another page if it doesn't seem to fit anywhere

**Comment by darrylpargeter** [comment]
kool, will put it not the main page for now, then can go from there

**Comment by jenkoian** [comment]
Sounds good 👍
