### ISSUE TITLE
Pull request Status not updating; Still shows pending, long after approved.

### ISSUE THREAD

**Issue by msj2** [jenkoian/hacktoberfest-checker#405]
Pull request Status not updating; Still shows pending, long after approved.

**Comment by jenkoian** [comment]
Hey @msj2, it takes 7 days for your pending PRs to not be pending, so I think if you check back tomorrow it should be showing correctly :)

**Comment by msj2** [comment]
Hi @jenkoian, 
Yes, I'm aware of the 7 day period.
On hacktober Site, PR's are showing completed, but here it doesn't.

I was assuming hacktoberfest-checker shows Status of PR's form Hacktober Site in real time.

So, there's 24 hour delay.

Best to put this up.

**Comment by jenkoian** [comment]
ah thanks for the clarification @msj2 we must be calculating the 7 day period slightly differently, perhaps they are taking into account time zones better than I am. Anyhow, it seems to have worked out now.
