### ISSUE TITLE
Enable gzip compression

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#413]
https://medium.com/@victor.valencia.rico/gzip-compression-with-node-js-cc3ed74196f9

**Comment by MrLucyfer** [comment]
Hey can you assign this to me?

**Comment by jenkoian** [comment]
@MrLucyfer done!

**Comment by willi123yao** [comment]
This issue can be closed via #419 as compression has been added in the PR and merged.
