### ISSUE TITLE
Create a basic robots.txt

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#415]
https://support.google.com/webmasters/answer/6062596?hl=en

**Comment by shivambhatia5432** [comment]
Is this issue still open?

**Comment by jenkoian** [comment]
@shivambhatia5432 Yup!

**Comment by nikikalwar** [comment]
Hi I am also interested, Can you please assign it to me @jenkoian

**Comment by shivambhatia5432** [comment]
Can you guide me a little bit in this issue?

**Comment by jenkoian** [comment]
Fixed in https://github.com/jenkoian/hacktoberfest-checker/pull/418

**Comment by Jaagrav** [comment]
@jenkoian https://hacktoberfest.digitalocean.com/hacktoberfest-update Please update your issues by adding "hacktoberfest-accepted" label.

**Comment by jenkoian** [comment]
Thanks @Jaagrav I think because the repo is already tagged with the 'hacktoberfest' topic all PRs in this repo quality. I do need to update the logic of the app though.
