### ISSUE TITLE
Travis build

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#42]
Although there are [no tests yet](https://github.com/jenkoian/hacktoberfest-checker/issues/16) we could still build on travis to lint etc. Don't want to go mad with JS build stuff but some basic linting should be ok.

**Comment by MiguhRuiz** [comment]
I'm working on this. 👍 

I need to be authorized in the repository in order to connect it to Travis CI

**Comment by troy0820** [comment]
@MiguhRuiz If you fork it, can't you just add the PR after it's set up in your repo?  This way the changes will effect this repo after it's merged.

**Comment by MiguhRuiz** [comment]
#44 As you can see you'll need to implement some test in order to pass the build but the work of implementing Travis CI is done. 👍

**Comment by JakenHerman** [comment]
This is fixed in https://github.com/jenkoian/hacktoberfest-checker/pull/44
