### ISSUE TITLE
Change PR status display

### ISSUE THREAD

**Issue by willi123yao** [jenkoian/hacktoberfest-checker#425]
Right now, the status of the PR (e.g. _Pending_) is displayed using italic text beside the PR. 

Will it be better to wrap it around in a component like a tag/label such as one with a rounded border and solid color? It can look similar to the labels used on Github issues/PRs.

**Comment by sagarsaud51** [comment]
Hello @willi123yao 

Is this issue still open? I'm interested in picking up this issue. 

Hoping it would be labeled as hacktoberfest.
