### ISSUE TITLE
Add dark and light mode

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#426]
The official site lets you switch easily between dark and light mode. This is neat but I think just doing it on users os settings is fine: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by testerslol123** [comment]
Can I take this hacktoberfest challenge?
Thank you :)

**Comment by jenkoian** [comment]
@testerslol123 sure, feel free to make a PR. I'm open to a switch, but also fine with it just using the `prefers-color-scheme` media query...if you do add a switch it should default to the media query if possible.

**Comment by testerslol123** [comment]
@jenkoian may I know where to contact you? Just for easy contact if have some problem.
I just stuck in some problem like 
<link rel="icon" type="image/x-icon" href="%REACT_APP_HOSTNAME%/img/favicon.ico" />

It just said undefined or some things about
URIError: Failed to decode param '/%REACT_APP_HOSTNAME%/img/favicon.ico'

Thank you

**Comment by jenkoian** [comment]
@testerslol123 have you created your `.env` file based from https://github.com/jenkoian/hacktoberfest-checker/blob/master/.env.example#L11 ?

**Comment by testerslol123** [comment]
@jenkoian currently because some circumstance, I would like to give this feature to another person to develop.
I may joining after this hacktoberfest, would take some time trying to catch up this react things.

Thanks

**Comment by LMulvey** [comment]
Hey, I'll grab this if nobody else has!
