### ISSUE TITLE
Is it supposed to add contributions from your own repos marked with Hacktoberfest issues?

### ISSUE THREAD

**Issue by matthamil** [jenkoian/hacktoberfest-checker#43]
^
Is it supposed to add contributions that you make from your own repos marked with Hacktoberfest issues?

**Comment by qk4** [comment]
It should only count Pull Requests. As i understand it.

**Comment by matthamil** [comment]
I guess I should have worded that better. Should it be counting Pull Requests that you make for your own repositories marked with Hacktoberfest issues?

**Comment by jenkoian** [comment]
@matthamil as far as I'm aware any pull request counts, be it your own repository or someone else's

**Comment by Superhuman07** [comment]
Hi 
hello all I am not able to set label to Hackoctoberfest can anybody explain it to me why?
The label field just shows normal lables not hackoctoberfest.

**Comment by matthamil** [comment]
@Superhuman07 You need to click on `Issues` -> `Labels` -> `New label` and then create one with the name `Hacktoberfest`. You can choose any color you want for your Hacktoberfest issues too.

**Comment by Superhuman07** [comment]
yeah thanks man! got it! 👍

**Comment by Superhuman07** [comment]
One more thing @matthamil 
Do the PR should be also labelled as

> Hacktoberfest

**Comment by matthamil** [comment]
Nope, they do not need a Hacktoberfest tag on the PR. They don't need the
Hacktoberfest issue to be present in the repo either. You just need to
submit 4 PRs during this month.

**Comment by Superhuman07** [comment]
@matthamil Ok cool!
Then I will be waiting for my tee 😄 
Cheers! 👍
