### ISSUE TITLE
filter PR's if their repo has hacktoberfest label

### ISSUE THREAD

**Issue by sandeep-chahal** [jenkoian/hacktoberfest-checker#435]

**Comment by RascalTwo** [comment]
Hey, I can add this functionality.

**Comment by jenkoian** [comment]
Thanks @RascalTwo I think you got it but to quote the blog post (https://hacktoberfest.digitalocean.com/hacktoberfest-update):

```
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)
```

Also here's the PR to the official hacktoberfest repo for reference: https://github.com/digitalocean/hacktoberfest/pull/596/files

**Comment by jenkoian** [comment]
They've also increased the review period to 2 weeks (14 days) so need to update this as well: https://github.com/jenkoian/hacktoberfest-checker/blob/c6b98fd41edf70bbeec65bf6caee7060523a1d16/api/controllers/pr/findPrs/index.js#L45
