### ISSUE TITLE
Update social og image

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#444]
Still using the one from last year: https://github.com/jenkoian/hacktoberfest-checker/blob/master/public/img/og.png

**Comment by HunainHumail** [comment]
What image do you want me to add? I would like to work on this issue and update the image. Please assign me this issue
Thanks

**Comment by jenkoian** [comment]
@HunainHumail something similar to the existing image but with updated fonts would be fine. Here's the font I use for the 'fest' on the site: https://fonts.google.com/specimen/Press+Start+2P

**Comment by galElmalah** [comment]
Is someone actively working on this issue? if not ill be happy to contribute
@jenkoian

**Comment by jenkoian** [comment]
@galElmalah Not heard from @HunainHumail so go for it

**Comment by galElmalah** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/40733145/95736215-9a62fd00-0c8e-11eb-8a16-be753976a250.png)

**Comment by jenkoian** [comment]
@galElmalah Perfect

**Comment by galElmalah** [comment]
Cool ill open a PR 😄

**Comment by jenkoian** [comment]
Fixed in #457
