### ISSUE TITLE
Only load social JS on the user result page

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#447]
By using an if similar to https://github.com/jenkoian/hacktoberfest-checker/blob/master/public/index.html#L70 we should be able to only load twitter and facebook code on the user page which is the only place it is ever used (for people to share their results).

https://github.com/jenkoian/hacktoberfest-checker/blob/master/public/index.html#L77-L108

This means not loading a needless JS script on the homepage.

**Comment by Farelion** [comment]
Hey i've made pull request for this issue "Move twitter and fb scripts to user page only", it worked locally, let me know if i helped!

**Comment by jenkoian** [comment]
Fixed in #450
