### ISSUE TITLE
Add preconnect for 3rd party assets

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#449]
<img width="789" alt="Screenshot 2020-10-06 at 22 29 04" src="https://user-images.githubusercontent.com/131355/95262101-71bcac80-0823-11eb-9c71-a6e2b683e086.png">

https://web.dev/uses-rel-preconnect/

**Comment by palak001** [comment]
I would like to work on this issue.

**Comment by jenkoian** [comment]
Fixed in #452
