### ISSUE TITLE
PRs marked invalid don't count

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#48]
https://twitter.com/digitalocean/status/784388561521012736

Should just be a case of updating the following: https://github.com/jenkoian/hacktoberfest-checker/blob/master/index.js#L56

Before:
`q: 'created:2016-09-30T00:00:00-12:00..2016-10-31T23:59:59-12:00+type:pr+is:public+author:' + username`

After:
`q: '-label:invalid+created:2016-09-30T00:00:00-12:00..2016-10-31T23:59:59-12:00+type:pr+is:public+author:' + username`

**Comment by Godsend72** [comment]
Hello, I am interested in this. Are you saying that only that one line should be changed? If so isn't that a bit too easy?
