### ISSUE TITLE
Social Sharing

### ISSUE THREAD

**Issue by allonsyalexa** [jenkoian/hacktoberfest-checker#52]
Once you "check" each username, it would be really nice to have a social sharing button for Twitter - using the #hacktoberfest hashtag and tagging the user.

**Comment by Ferbla** [comment]
I can give this a try. Would Twitter, Facebook and Google+ work?

**Comment by allonsyalexa** [comment]
That would be great! That's for considering the suggestion 😊

**Comment by allonsyalexa** [comment]
Thanks*

**Comment by 123aswin123** [comment]
Hi , please check #62 and tell me if there are any issues!

**Comment by 123aswin123** [comment]
@jenkoian Please check #62 again! Thanks!

**Comment by allonsyalexa** [comment]
This looks perfect!
