### ISSUE TITLE
Reskin app

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#566]
New year, new colours, should update this app to reflect. Reminder we don't just steal assets or fonts but go for a close match.

**Comment by danmana** [comment]
Hi, I'd like to pick this up.

What should be changed?
* pink -> orange
* logo
* button colors?
* background color?

Also, I'm thinking about how to make this easier to change next year.
Would it be better to define some `hack-primary`, `hack-secondary` colors in tailwind (plus dark mode variants), so we don't have to replace `pink` with `orange` everywhere in HTML/css?
Any feedback is welcome, I'm new to tailwind and I'm not sure what are the best practices.

**Comment by jenkoian** [comment]
Yeah something along the same sort of theme as https://hacktoberfest.digitalocean.com/

Tailwind suggestion sounds good :)

**Comment by jenkoian** [comment]
Closed by #593
