### ISSUE TITLE
Replace travis with github actions

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#568]
Travis have been doing some not so good things this past year, let's move to github actions.

**Comment by vincentrohde** [comment]
That sounds quite interesting. I'd love to do this 💯

**Comment by aakhtar3** [comment]
@jenkoian I can work on this.

**Comment by aakhtar3** [comment]
PR is ready for merge
https://github.com/jenkoian/hacktoberfest-checker/pull/590

**Comment by jenkoian** [comment]
Closed by #590
