### ISSUE TITLE
Update to latest version of tailwind

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#569]
Currently on 1.9.4, 2.2.16 is latest at time of writing.

**Comment by EugeneGohh** [comment]
Hi, I would like to contribute to this. May I work on this issue?

**Comment by jenkoian** [comment]
@EugeneGohh there is a PR open already https://github.com/jenkoian/hacktoberfest-checker/pull/570 but I envisaged there'd be more to it than that so happy for you to take a look also.

**Comment by aneeshpanda** [comment]
Hi, I would like to take up this issue!
