### ISSUE TITLE
Add support for github and gitlab lookups with different usernames

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#577]
Currently we have a single input for a username, this will check github and gitlab for PRs (or MRs) for that user. However, it's possible a user has a different username on gitlab to github. This use case is currently not supported.

See [this section of the readme](https://github.com/jenkoian/hacktoberfest-checker/blob/master/README.md?plain=1#L18) for an idea of how this could be solved.

**Comment by dolamanee6122** [comment]
Hey @jenkoian , please assign this issue to me.

**Comment by jenkoian** [comment]
@dolamanee6122 no need to assign, just PR away :)

**Comment by babu1998** [comment]
I can work on this after the fallback PR is merged.

**Comment by babu1998** [comment]
We can make registration compulsory and ask the user for github and gitlab id at registration. Then integate that data in the react app.

**Comment by jenkoian** [comment]
> We can make registration compulsory and ask the user for github and gitlab id at registration. Then integate that data in the react app.

This is pretty much what the official site does and there'd be no point in us doing the same
