### ISSUE TITLE
Replace promises with async/await

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#584]
The API side of the app makes heavy use of promises. Let's replace them with async/await for improved readability.

**Comment by GregSithole** [comment]
Hey Please assign this to me, I'll do it

**Comment by precious-adeyinka** [comment]
Can I work on this too? @jenkoian

**Comment by SangramBarge** [comment]
Hi Please assign me this

**Comment by jenkoian** [comment]
Thanks everyone for the interest, I'm not going to assign to anyone, just submit a PR and let's see how we get on :)

**Comment by GregSithole** [comment]
@jenkoian Let me know if you have issues with the pull request but that should do it.
