### ISSUE TITLE
Add support for fallback to gitlab if user doesn't exist on github

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#585]
Currently the app will error if the user is not found on github. We should improve this to fallback to gitlab if the user doesn't exist on github then only erroring if they then don't exist on gitlab.

**Comment by babu1998** [comment]
Have made a PR for this issue https://github.com/jenkoian/hacktoberfest-checker/pull/592

**Comment by jenkoian** [comment]
Closed by #592
