### ISSUE TITLE
FAQs Fix

### ISSUE THREAD

**Issue by Mannuel25** [jenkoian/hacktoberfest-checker#601]
![IMG_20211010_002227](https://user-images.githubusercontent.com/68563757/136676137-cb1dcb7c-884a-4146-982d-f7276e290274.jpg)

When I clicked the FAQs button in the homepage it redirects me to the FAQs page, but I can still see the FAQs button below in the FAQs page (which when clicked refers to the current page I'm in). I feel there should be a button that redirects the user back to the homepage instead of the FAQs button being there.

**Comment by jenkoian** [comment]
Fair 👍 are you able to PR?
