### ISSUE TITLE
Input validation required

### ISSUE THREAD

**Issue by vimode** [jenkoian/hacktoberfest-checker#709]
Hello,

If you search a username with an empty space before the username, it will throw an error. 
I think an input validation should be added on submit which will make sure that any whitespace before the input value is removed. 

AFAIK, github usernames cannot have spaces before anyway, so that shouldn't be a problem either. Isn't it?

**Comment by jenkoian** [comment]
Sounds like we just need to add a [trim()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) call. Would you like to add a PR for this?

**Comment by vimode** [comment]
Sure I will give it a go.
