### ISSUE TITLE
[FEAT] The text on the footer seems disorganized 

### ISSUE THREAD

**Issue by Johnnyteck** [jenkoian/hacktoberfest-checker#710]
An align center would work best for thus text. Kindly assign thus to me and consider it fixed 😁
![IMG_20221005_134717](https://user-images.githubusercontent.com/73708569/194064780-3bfeb9fb-4bd5-4a9f-9c39-05393aab1886.jpg)

**Comment by vimode** [comment]
Its because of the link color blending with the background color discussed in #705  
The PR #706 should fix this I suppose.

**Comment by Johnnyteck** [comment]
Alright then, great.
