### ISSUE TITLE
Need to ignore closed pull requests

### ISSUE THREAD

**Issue by lokeshh** [jenkoian/hacktoberfest-checker#72]
It shouldn't include closed pull requests in the counting.

**Comment by drewvolz** [comment]
@lokeshh Digital Ocean's response on closed PRs... http://disq.us/p/1cqbhoi

> Closed PRs will count as well, as long as the maintainer does not report it as spam. So all genuine attempts to contribute, even if they end up not being merged for some reason, will count.

**Comment by lokeshh** [comment]
Nice
