### ISSUE TITLE
README.md does not have a contributing section

### ISSUE THREAD

**Issue by icextreme** [jenkoian/hacktoberfest-checker#725]
It seems like isn't a contributing section in README.md, but there is a CONTRIBUTING.md in the repo. It would be good if there is a section in the README that links to the contributing section so that it is easier to find.

What are your thoughts on the idea? I can help work on this if it is a good idea.

**Comment by jenkoian** [comment]
Sure, go for it

**Comment by icextreme** [comment]
Thank you!
