### ISSUE TITLE
Add a filter

### ISSUE THREAD

**Issue by mezotv** [jenkoian/hacktoberfest-checker#726]
Add a filter to filter out excluded or invalid prs to not display wrong information. I don't know if this is possible but I guess its worth a shot

**Comment by jenkoian** [comment]
Do you have an example of what you mean? We do already so some filtering on this for both github and gitlab, e.g, https://github.com/jenkoian/hacktoberfest-checker/blob/28570e4a597a2fd1febfb36177859b70ae7bdc80/api/controllers/pr/findPrs/gitlab/index.ts#L48

**Comment by mezotv** [comment]
Sure! For example it shows this as pending on the checker website 
![image](https://user-images.githubusercontent.com/68947960/195321553-65833cab-3b2a-447f-b255-2b1dd822be2e.png)
But on the hacktoberfest website it shows excluded 
![image](https://user-images.githubusercontent.com/68947960/195321674-189284c9-5c56-427f-ac26-6c618c91b53a.png)

**Comment by jenkoian** [comment]
Ah cool, that's a good test - thanks! Unfortunately Digital Ocean maintains a list of excluded repositories which we do not have access to, so we are unable to support this feature sadly :(

**Comment by mezotv** [comment]
Ahh that's unfortunate. Still a cool project!
