### ISSUE TITLE
Seems down?

### ISSUE THREAD

**Issue by Sumith1896** [jenkoian/hacktoberfest-checker#76]
![hacktober](https://cloud.githubusercontent.com/assets/9217608/19598158/e2bb330c-97b6-11e6-8eb3-aad4a749eb72.png)

**Comment by jenkoian** [comment]
Yep: https://news.ycombinator.com/item?id=12759520

**Comment by Sumith1896** [comment]
Thanks @jenkoian for the info, seems like we can close this then
