### ISSUE TITLE
Couldn't find any data or we hit an error, err try again?

### ISSUE THREAD

**Issue by jtemporal** [jenkoian/hacktoberfest-checker#77]
yesterday everything was fine... Now we are getting this error:

![screenshot from 2016-10-21 11-04-58](https://cloud.githubusercontent.com/assets/6595551/19599193/4c6757ec-977e-11e6-9f7e-9d5adf19204c.png)

anything we can to help get it to work again ? =)

**Comment by jenkoian** [comment]
Hey @jtemporal thanks for the offer of help! :)

It seems the whole internet is suffering from issues today and we're being affected too, more info here: https://news.ycombinator.com/item?id=12759520

**Comment by jenkoian** [comment]
Should be back now - also just pushed up #71 so should be even sweeter :)

**Comment by jtemporal** [comment]
Awesome!! thanks ;)
