### ISSUE TITLE
Incorrect Count

### ISSUE THREAD

**Issue by Linell** [jenkoian/hacktoberfest-checker#78]
I'm seeing _way_ more pull requests submitted than I've actually made.
![screen shot 2016-10-21 at 8 34 41 am](https://cloud.githubusercontent.com/assets/1231554/19600148/4cbc83e4-9769-11e6-9382-9dc96b78c3d1.png)

I believe I should have like two. Trying a couple of other usernames, it seems like the incorrect ones are present for them as well.

**Comment by jenkoian** [comment]
Oh yep, apparently I've made 104, I'm nowhere near that good! Will revert the last commit which may have caused it. 👍

**Comment by jenkoian** [comment]
Ok sorted, thanks so much for reporting 👍
