### ISSUE TITLE
Hacktoberfest 2017 coming soon

### ISSUE THREAD

**Issue by ch3nkula** [jenkoian/hacktoberfest-checker#96]
You may want to start looking at updating (UI/UX) this tool as the program is coming up again soon (2017 series). Here is a link to the new design page: https://hacktoberfest.digitalocean.com/. 👍

**Comment by jenkoian** [comment]
Thanks for the heads up @ch3nkula! I did email DigitalOcean to find out more but still awaiting response, so cheers for this!

**Comment by ch3nkula** [comment]
Okay @jenkoian. Great! Let's wait for their reply then. Meanwhile, this is a great tool. I am pretty sure it was used by many to know their Hacktoberfest status :).

**Comment by arguiot** [comment]
Hacktoberfest is here, so when will you guys think the website will be updated?

**Comment by jenkoian** [comment]
@arguiot thanks for your interest, will be pushing the new version up tomorrow

**Comment by jenkoian** [comment]
Have updated the app, will deploy before the 1st. Let me know if you have any questions, I've tried to strip it back a bit to keep it appealing to beginners. I will add some improvement tickets over the next few days.

Cheers! 🎃

**Comment by ch3nkula** [comment]
Thanks very much @jenkoian. 👍  I don't have any questions for now. :)

**Comment by salman-bhai** [comment]
@jenkoian App Deployment not yet done kya?

We're actually organising a meetup this year and that's why just wanted to double-check?

**Comment by jenkoian** [comment]
@salman-bhai not done yet, was going to do it later today if that's alright? Let me know if you need it sooner and i'll prioritise :)

**Comment by salman-bhai** [comment]
No tonight sounds good! And great work on the repo man!

**Comment by jenkoian** [comment]
Done, let me know if you run into any issues, not managed to spend too long testing due to working next door to a pub 👍

**Comment by salman-bhai** [comment]
This is our meetup repo! Gave you credits in the description. Let me know if I need to add anything else about you!
